apiVersion: v1
kind: Pod
metadata:
  name: docker-cwl-pod
spec:
  restartPolicy: Never
  serviceAccountName: airflow-worker

  containers:
  - name: cwl-docker
    # image: ghcr.io/unity-sds/unity-sps/sps-docker-cwl:2.0.0-alpha.1
    image: ghcr.io/unity-sds/unity-sps/sps-docker-cwl:develop4
    imagePullPolicy: Always
    command: ["/usr/share/cwl/docker_cwl_entrypoint.sh"]
    securityContext:
      privileged: true
