openapi: 3.0.0
info:
  version: 0.2.0
  title: App Package API
  description: Service for application package generation

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer

security:
  - bearerAuth: []

servers:
  - url: api.dev.mdps.mcp.nasa.gov

paths:
  /ads-acb/mcp-clone:
    get:
      summary: Begins the MCP Clone process
      requestBody:
        description: For API parameters clone_url (required), apg_tag (optional), and uag_tag (optional)
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clone_url:
                  type: string
                  description: the url of a public git repository from which to build an app-package, e.g. https://github.com/unity-sds/unity-example-application
                  example: https://github.com/unity-sds/unity-example-application
                apg_tag:
                  type: string
                  description: the tag (version) of https://github.com/unity-sds/app-pack-generator used in build process with default value 0.4.1
                  example: 0.4.1
                uag_tag:
                  type: string
                  description: the tag (version) of https://github.com/unity-sds/unity-app-generator used in build process with default value 0.3.0
                  example: 0.3.0
              required:
                - clone_url
      responses:
        '200':
          description: Successfully submitted a job
          content:
            application/json:
              schema:
                type: object
                properties:
                  clone_url:
                    type: string
                  log_group_name:
                    type: string
                  apg_tag:         # app-pack-gen version (tag) used in build process
                    type: string
                  uag_tag:         # unity-app-gen version (tag) used in build process
                    type: string
