# coding: utf-8

"""
    App Package API

    Service for application package generation

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from unity_sds_apgs_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_ads_acb_mcp_clone_get(self) -> None:
        """Test case for ads_acb_mcp_clone_get

        Begins the MCP Clone process
        """
        pass


if __name__ == "__main__":
    unittest.main()
