name: Integration Tests

on:
  schedule:
    # Runs around midnight Pacific Time (UTC-7)
    # Doesn't account for daylight saving transitions
    - cron: "0 7 * * *"
  workflow_dispatch:
    inputs:
      MCP_VENUE_DEV_AIRFLOW_ENDPOINT:
        description: "Base URL for the Airflow endpoint in MCP Venue Dev (i.e. http://abc.def.ghi:port-number)"
        type: string
      # MCP_VENUE_TEST_AIRFLOW_ENDPOINT:
      #   description: "Base URL for the Airflow endpoint in MCP Venue Test (i.e. http://abc.def.ghi:port-number)"
      #   type: string
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"

    - name: MCP Venue Dev - Integration tests
      continue-on-error: true
      run: |
        pytest -vv --gherkin-terminal-reporter \
        unity-test/system/integration \
        --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_DEV_AIRFLOW_ENDPOINT || vars.MCP_VENUE_DEV_AIRFLOW_ENDPOINT }}
      env:
        AIRFLOW_WEBSERVER_PASSWORD: ${{ github.secrets.MCP_VENUE_DEV_AIRFLOW_WEBSERVER_PASSWORD }}

    # - name: MCP Venue Test - Integration tests
    #   continue-on-error: true
    #   run: |
    #     pytest -vv --gherkin-terminal-reporter \
    #     unity-test/system/integration \
    #     --airflow-endpoint=${{ github.event.inputs.MCP_VENUE_TEST_AIRFLOW_ENDPOINT || vars.MCP_VENUE_TEST_AIRFLOW_ENDPOINT }}
