name: pre-commit

on:
  pull_request:
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Read .terraform-version
      id: tf_version
      run: echo "TF_VERSION=$(cat .terraform-version)" >> $GITHUB_ENV
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
    - name: Install Hadolint for pre-commit hook
      run: |
        wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
        chmod +x /usr/local/bin/hadolint
    # - name: Install dependencies for Python tests
    #   run: |
    #     pip install -e ".[test]"
    # - uses: pre-commit/action@v3.0.1
    #   with:
    #     extra_args: --all-files
    # - name: Test with pytest
    #   run: |
    #     pytest -vv --gherkin-terminal-reporter unity-test/unit
