name: Smoke Tests with Pytest

on:
  schedule:
    # Runs around midnight Pacific Time (UTC-7)
    # Doesn't account for daylight saving transitions
    - cron: "0 7 * * *"
  workflow_dispatch:
    inputs:
      AIRFLOW_ENDPOINT:
        description: "Base URL for the Airflow endpoint (i.e. http://abc.def.ghi:port-number)"
        type: string

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"

    - name: Run smoke tests
      run: |
        pytest -vv --gherkin-terminal-reporter
        unity-test/system/smoke
        --airflow-endpoint=${{ github.event.inputs.AIRFLOW_ENDPOINT || vars.MCP_DEV_AIRFLOW_ENDPOINT }}
